{% set version = "2.2.4" %}

package:
  name: libgdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: 441eb1d1acb35238ca43a1a0a649493fc91fdcbab231d0747e9d462eea192278
  patches:
    # Fixes compilation problems with JPEG.
    # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
    - disable_jpeg12.patch
    # BUILT_AS_DYNAMIC_LIB.
    - windowshdf5.patch
    # Use multiple cores on Windows.
    - multiprocessor.patch

build:
  number: 5
  skip: True  # [win and py36]
  features:
    - vc9  # [win and py27]
    - vc14  # [win and (py35 or py36)]

requirements:
  build:
    - boost 1.66.0  # only need to get conda-forge's libkml instead of defaults
    - python  # [win]
    - m2w64-xz  # [win]
    - cmake  # [win]
    - curl >=7.54.1,<8
    - expat 2.2.*
    - freexl
    - geos 3.6.2
    - geotiff
    - giflib 5.1.*  # [not win]
    - hdf4
    - hdf5 1.10.1
    - jpeg 9*
    - json-c 0.12.1  # [not win]
    - kealib 1.4.7
    - libdap4 3.18.*  # [not win]
    - libkml 1.3.0  # [not win]
    - libnetcdf 4.4.*  # [win and py2k]
    - libnetcdf 4.5.*  # [not (win and py2k)]
    - libpng >=1.6.32,<1.6.35
    - libspatialite
    - libtiff >=4.0.8,<4.0.10
    - openjpeg 2.3.*
    - poppler 0.61.*  # [not win]
    - postgresql
    - proj4 4.9.3
    - sqlite 3.20.*
    - xerces-c 3.2.0
    - zlib 1.2.11  # [not win]
    - xz 5.2.*
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
  run:
    - boost 1.66.0  # only need to get conda-forge's libkml instead of defaults
    - curl >=7.54.1,<8
    - expat 2.2.*
    - freexl
    - geos 3.6.2
    - geotiff
    - giflib 5.1.*  # [not win]
    - hdf4
    - hdf5 1.10.1
    - jpeg 9*
    - json-c 0.12.1  # [not win]
    - kealib 1.4.7
    - libdap4 3.18.*  # [not win]
    - libkml 1.3.0  # [not win]
    - libnetcdf 4.4.*  # [win and py2k]
    - libnetcdf >=4.5  # [not (win and py2k)]
    - libpng >=1.6.32,<1.6.35
    - libpq
    - libspatialite
    - libtiff >=4.0.8,<4.0.10
    - openjpeg 2.3.*
    - poppler 0.61.*  # [not win]
    - proj4 4.9.3
    - sqlite 3.20.*
    - xerces-c 3.2.0
    - zlib 1.2.11  # [not win]
    - xz 5.2.*
    - vc 9  # [win and py27]
    - vc 14  # [win and (py35 or py36)]
    - libstdcxx-ng  # [linux]

test:
  files:
    - test_data
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'The Geospatial Data Abstraction Library (GDAL).'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
