{% set version = "2.3.1" %}

package:
  name: libgdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: 9c4625c45a3ee7e49a604ef221778983dd9fd8104922a87f20b99d9bedb7725a
  patches:
    # BUILT_AS_DYNAMIC_LIB.
    - windowshdf5.patch
    # Use multiple cores on Windows.
    - multiprocessor.patch
    # disable 12 bit jpeg on Windows as we aren't using internal jpeg
    - disable_jpeg12.patch

build:
  number: 2
  skip: True  # [win and vc<14]

requirements:
  build:
    - pkg-config  # [not win]
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - m2w64-xz  # [win]
    - curl
    - expat
    - freexl
    - geos
    - geotiff
    - giflib  # [not win]
    - hdf4
    - hdf5
    - jpeg
    - json-c  # [not win]
    - kealib
    - libdap4  # [not win]
    - libkml  # [not win]
    - libnetcdf
    - libpng
    - libspatialite
    - libtiff
    - openjpeg
    - poppler  # [not win]
    - postgresql
    - proj4
    - sqlite
    - xerces-c
    - zlib  # [not win]
    - xz
  run:
    - curl
    - expat
    - freexl
    - geos
    - geotiff
    - giflib  # [not win]
    - hdf4
    - hdf5
    - jpeg
    - json-c  # [not win]
    - kealib
    - libdap4  # [not win]
    - libkml  # [not win]
    - libnetcdf
    - libpng
    - libpq
    - libspatialite
    - libtiff
    - openjpeg
    - poppler  # [not win]
    - proj4
    - sqlite
    - xerces-c
    - zlib  # [not win]
    - xz

test:
  files:
    - test_data
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'The Geospatial Data Abstraction Library (GDAL)'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
