{% set version = "2.2.4" %}

package:
  name: libgdal
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: 441eb1d1acb35238ca43a1a0a649493fc91fdcbab231d0747e9d462eea192278
  patches:
    # Fixes compilation problems with JPEG.
    # https://lists.osgeo.org/pipermail/gdal-dev/2016-January/043443.html
    - disable_jpeg12.patch
    # BUILT_AS_DYNAMIC_LIB.
    - windowshdf5.patch
    # Use multiple cores on Windows.
    - multiprocessor.patch

build:
  number: 6

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - m2w64-xz  # [win]
    - curl
    - expat
    - freexl
    - geos
    - geotiff
    - giflib  # [not win]
    - hdf4
    - hdf5
    - jpeg
    - json-c  # [not win]
    - kealib
    - libdap4  # [not win]
    - libkml  # [not win]
    - libnetcdf 4.4.*  # [win and vc<14]
    - libnetcdf  # [not (win and vc<14)]
    - libpng
    - libspatialite
    - libtiff
    - openjpeg
    - poppler  # [not win]
    - postgresql
    - proj4
    - sqlite
    - xerces-c
    - zlib  # [not win]
    - xz
  run:
    - curl
    - expat
    - freexl
    - geos
    - geotiff
    - giflib  # [not win]
    - hdf4
    - hdf5
    - jpeg
    - json-c  # [not win]
    - kealib
    - libdap4  # [not win]
    - libkml  # [not win]
    - libnetcdf 4.4.*  # [win and vc<14]
    - libnetcdf  # [not (win and vc<14)]
    - libpng
    - libpq
    - libspatialite
    - libtiff
    - openjpeg
    - poppler  # [not win]
    - proj4
    - sqlite
    - xerces-c
    - zlib  # [not win]
    - xz

test:
  files:
    - test_data
  commands:
    - gdal_grid --version
    - gdal_rasterize --version
    - gdal_translate --version
    - gdaladdo --version
    - gdalenhance --version
    - gdalwarp --version
    - gdalinfo --formats
    - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gdal.org/
  license: MIT
  license_file: LICENSE.TXT
  summary: 'The Geospatial Data Abstraction Library (GDAL).'

extra:
  recipe-maintainers:
    - ocefpaf
    - kmuehlbauer
    - gillins
