travis:
  secure:
    BINSTAR_TOKEN: h2tVfJM8affI7VTPAKgvmaBCifPZIw/oMHAtSnA6YG8LuwUE3/26E8gpVz8+j2MSwusv/TDaW8z4eXgwarrwTdO2E28BwyZU9mtsbIFCRLq67gncBCEHlxOgVlIP+se3XRUA1K3Qy9MsawJOz3wEgqXe8pJCAf7TPU5u8oFm3H2YB/yDUPJNmdVEz2Q5GE82pLGzud6XoK3lgpeo6ElZaTCW31UUOoD5FEOJ/XNFBJ6E868JC0JXBzZr0T5RLv2ZblzazAbz0MuA+UPqgoytO9jFmaePzc4CNGvLLcR7ln0LTDQXjRstzN0GZDp3cu+qHz0J26RfUu+suSImwB5kAlC2OiFhYK9Xfv/kQR8Uxo8Xp/zctWx2hAtmtMlNo7gOdZtnPhz/te1JQzlH3M8Oj3sLtRmsFV8mgrYyjDWme/7SnslYc1CDMdVcvbcrR+YWRKlFjKSf/ggNMLAMO3Zw6m+gW8m0ASu6n85q7+5xUovIw6JTSIUvUf0BOIkLLS2lhc4DUQJJ68BLfQm3oGN5ts80REK5U8d6VkiNGF8dOzjJuml7uM9UIgZP1wmQEJ+hfPuqj+9nEwYUIp1AKQL8fuq8fj1RfUB5/nZQrJUM+8I3CTnYpEGd8RHCdK9uj1Cng2Re+PG0vJ2WLL3xCrFhzzJA8anFkjyT35CKaKb9cH4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
provider:
  osx: circle