travis:
  secure:
    BINSTAR_TOKEN: WI3LOiFDyucDcy0URSDYmT6c8qgxKtghX9ngoPtTu0VJWskpunNb80qophKideKf8qNed68JjzI+aHi9NJXoptqOLgNUtQ0Ngr8HDRYt5mGF6J3ltin0D+cACch8M1tTEjqI82wvbrstWijjFoR3ru25c3veenFkW7vVvVBGIQp2qxEdkkmgoInBrlfiCGYSxpt4lGhbgruaArltJhTK+gewmjvqo5oYNtwBz360RUrT+EJFtqyF2XD0T7i4Gi1e1TY2qHlP3Han9B0z1yNqWMEENIuSqFKYRMN+IkvnNBLrwsXQGWf/T1whDTLGH/Byxu2xxjaJnp7HUIICBZMBAgd8njvpclM6HwWu0d9yxnjUDFonqyt/EHaoe8VeNKWJiVqRixdhUtWxxcDDPdYEJuz9xyzN0N+XX+qSzDGMJave6wYMy21VSUNmq0LmOlmt/UGXIvL4mfvirbG2k09V97lGvlurhCIbRlYjrNdA3K343HuFYKNWtfbK/rIuvrDlrsc+vsu5QYV38W1BgdOEI+IFPePxTRIz/pfKdmaj2YqHr/ffbInq2Dyd2SepaP1bcsEgfi4iCXQ9zWtjkTwbggph73k4d0jeEACWqOjEDMXsh96934CHqoxrHUVCzTR0UFBLxy9/JOQiws8kBjA0FffptP4IO818PR25rlalf0I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  osx: circle
